DROP TABLE IF EXISTS "BlogTranslation";
DROP TABLE IF EXISTS "BlogPooja";
DROP TABLE IF EXISTS "BlogTemple";
DROP TABLE IF EXISTS "BlogBlock";
DROP TABLE IF EXISTS "Blog";

DROP TYPE IF EXISTS "BlogBlockType";
DROP TYPE IF EXISTS "BlogStatus";