"use client";
import {useMutation,useQuery,useQueryClient} from "@tanstack/react-query";
import {ChevronDown,ChevronRight,RefreshCw,RotateCcw,Search} from "lucide-react";
import {Fragment,type ReactNode,useState} from "react";
import {Button} from "@/components/ui/button";
import {Card,CardContent,CardHeader,CardTitle} from "@/components/ui/card";
import {ConfirmDialog} from "@/components/ui/confirm-dialog";
import {Input} from "@/components/ui/input";
import {useToast} from "@/components/ui/toast-provider";
import {useDebounce} from "@/hooks/use-debounce";
import {cn,formatDate} from "@/lib/utils";
import {getSettlements,recoverSettlement,requestSettlementBackfill,retrySettlement} from "@/services/ops.service";
import type {Settlement,SettlementStatus,VendorBillStatus} from "@/types/ops";

const statuses:SettlementStatus[]=["PENDING","PROCESSING","PARTIAL","SETTLED","FAILED"];
const retryable=new Set<SettlementStatus>(["PENDING","PARTIAL","FAILED"]);
const styles:Record<SettlementStatus|VendorBillStatus,string>={PENDING:"border-amber-200 bg-amber-50 text-amber-800",PROCESSING:"border-blue-200 bg-blue-50 text-blue-800",PARTIAL:"border-orange-200 bg-orange-50 text-orange-800",SETTLED:"border-emerald-200 bg-emerald-50 text-emerald-800",FAILED:"border-red-200 bg-red-50 text-red-800",SYNCING:"border-blue-200 bg-blue-50 text-blue-800",SYNCED:"border-emerald-200 bg-emerald-50 text-emerald-800"};
function Badge({status}:{status:SettlementStatus|VendorBillStatus}){return <span className={cn("inline-flex rounded-full border px-2 py-0.5 text-xs font-semibold",styles[status])}>{status}</span>}
function errorMessage(error:unknown,fallback:string){const r=(error as {response?:{status?:number;data?:{message?:string|string[];error?:string}}}).response,d=r?.data?.message??r?.data?.error,m=Array.isArray(d)?d.join(" "):d;if(m)return r?.status===409?`Conflict: ${m}`:m;return r?.status===409?"Conflict: reconciliation is already running or the settlement is already reconciled.":fallback}
function money(value:number,currency:string){try{return new Intl.NumberFormat("en-IN",{style:"currency",currency,maximumFractionDigits:2}).format(value)}catch{return `${currency} ${value.toLocaleString("en-IN")}`}}
function ActionDialog({open,title,description,children,onClose}:{open:boolean;title:string;description:string;children:ReactNode;onClose:()=>void}){
 if(!open)return null;
 return <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/45 px-4" role="dialog" aria-modal="true" aria-labelledby="finance-action-title"><div className="w-full max-w-md rounded-lg border border-border bg-card shadow-xl"><div className="border-b border-border p-5"><h2 id="finance-action-title" className="text-base font-semibold">{title}</h2><p className="mt-2 text-sm leading-6 text-muted-foreground">{description}</p></div>{children}<div className="border-t border-border p-4"><Button type="button" variant="outline" className="w-full" onClick={onClose}>Cancel</Button></div></div></div>
}
function Summary({bills}:{bills:Settlement["vendorBills"]}){if(!bills.length)return <span className="text-muted-foreground">No bills</span>;const counts=bills.reduce<Partial<Record<VendorBillStatus,number>>>((a,b)=>{a[b.status]=(a[b.status]??0)+1;return a},{});return <div className="flex flex-wrap gap-1">{(["SYNCED","SYNCING","PENDING","FAILED"] as VendorBillStatus[]).map(s=>counts[s]?<span key={s} className="inline-flex items-center gap-1"><Badge status={s}/><small>{counts[s]}</small></span>:null)}</div>}
export function SettlementsTable(){
 const[search,setSearch]=useState(""),[status,setStatus]=useState<SettlementStatus|"">(""),[page,setPage]=useState(1),[expanded,setExpanded]=useState<Set<string>>(new Set()),[target,setTarget]=useState<Settlement|null>(null),[actionError,setActionError]=useState("");
 const[recoverOpen,setRecoverOpen]=useState(false),[confirmRecovery,setConfirmRecovery]=useState(false),[recoveryId,setRecoveryId]=useState(""),[recoveryValidation,setRecoveryValidation]=useState("");
 const[backfillOpen,setBackfillOpen]=useState(false),[backfillDays,setBackfillDays]=useState(3);
 const value=useDebounce(search.trim()),client=useQueryClient(),toast=useToast(),params={page,limit:20,...(value?{search:value}:{}),...(status?{status}:{})};
 const query=useQuery({queryKey:["settlements",params],queryFn:()=>getSettlements(params)});
 const mutation=useMutation({mutationFn:retrySettlement,onSuccess:async()=>{setTarget(null);setActionError("");toast.success("Settlement reconciliation retry started.");await client.invalidateQueries({queryKey:["settlements"]})},onError:e=>setActionError(errorMessage(e,"Unable to retry settlement reconciliation."))});
 const recover=useMutation({mutationFn:recoverSettlement,onSuccess:async()=>{setConfirmRecovery(false);setRecoveryId("");setActionError("");toast.success("Settlement recovered and reconciliation queued.");await client.invalidateQueries({queryKey:["settlements"]})},onError:e=>{setConfirmRecovery(false);setActionError(errorMessage(e,"Unable to recover settlement."))}});
 const backfill=useMutation({mutationFn:requestSettlementBackfill,onSuccess:async()=>{setBackfillOpen(false);setActionError("");toast.success("Recent settlement sync queued.");await client.invalidateQueries({queryKey:["settlements"]})},onError:e=>setActionError(errorMessage(e,"Unable to queue recent settlement sync."))});
 const actionsPending=mutation.isPending||recover.isPending||backfill.isPending;
 const toggle=(id:string)=>setExpanded(v=>{const n=new Set(v);if(n.has(id))n.delete(id);else n.add(id);return n});
 return <><Card><CardHeader className="flex flex-col gap-4 lg:flex-row lg:items-center lg:justify-between"><div><CardTitle>Settlement Tracker</CardTitle><p className="mt-1 text-sm text-muted-foreground">Track Razorpay settlements and Zoho vendor-bill reconciliation.</p></div><div className="flex flex-col gap-3"><div className="flex flex-wrap justify-end gap-2"><Button type="button" variant="outline" disabled={actionsPending} onClick={()=>{setActionError("");setRecoverOpen(true)}}>Recover Settlement</Button><Button type="button" disabled={actionsPending} onClick={()=>{setActionError("");setBackfillOpen(true)}}>Sync Recent Settlements</Button></div><div className="flex flex-col gap-3 sm:flex-row"><label className="relative block sm:w-80"><span className="sr-only">Search by settlement ID or UTR</span><Search className="pointer-events-none absolute left-3 top-1/2 h-4 w-4 -translate-y-1/2 text-muted-foreground"/><Input className="pl-9" placeholder="Settlement ID or UTR" value={search} onChange={e=>{setSearch(e.target.value);setPage(1)}}/></label><label><span className="sr-only">Filter by status</span><select className="h-10 rounded-md border border-border bg-card px-3 text-sm" value={status} onChange={e=>{setStatus(e.target.value as SettlementStatus|"");setPage(1)}}><option value="">All statuses</option>{statuses.map(s=><option key={s}>{s}</option>)}</select></label></div></div></CardHeader>
<CardContent className="overflow-x-auto p-0">{query.error&&<div role="alert" className="mx-5 mb-4 flex items-center justify-between rounded-md border border-red-200 bg-red-50 px-3 py-2 text-sm text-destructive"><span>{errorMessage(query.error,"Unable to load settlements.")}</span><Button variant="outline" size="sm" onClick={()=>void query.refetch()}><RefreshCw className="h-4 w-4"/>Retry</Button></div>}{actionError&&<div role="alert" className="mx-5 mb-4 rounded-md border border-red-200 bg-red-50 px-3 py-2 text-sm text-destructive">{actionError}</div>}
<table className="w-full min-w-[1200px] text-left text-sm"><thead className="border-b border-border bg-muted text-xs uppercase text-muted-foreground"><tr><th className="w-12 px-3 py-3"><span className="sr-only">Expand</span></th>{["Razorpay settlement","UTR","Amount / fees / tax","Provider date","Status","Payments","Zoho bills","Last error","Action"].map(h=><th key={h} className={cn("px-3 py-3",h==="Action"&&"text-right")}>{h}</th>)}</tr></thead><tbody className="divide-y divide-border">
{query.isLoading&&<tr><td colSpan={10} className="px-5 py-10 text-center text-muted-foreground">Loading settlements...</td></tr>}
{query.data?.items.map(s=>{const open=expanded.has(s.id);return <Fragment key={s.id}><tr className="align-top"><td className="px-3 py-4"><Button variant="ghost" size="icon" aria-expanded={open} aria-controls={`bills-${s.id}`} aria-label={`${open?"Collapse":"Expand"} vendor bills for ${s.providerSettlementId}`} onClick={()=>toggle(s.id)}>{open?<ChevronDown className="h-4 w-4"/>:<ChevronRight className="h-4 w-4"/>}</Button></td><td className="px-3 py-4 font-semibold">{s.providerSettlementId}</td><td className="px-3 py-4">{s.utr||"-"}</td><td className="px-3 py-4"><b>{money(s.amount,s.currency)}</b><p className="mt-1 text-xs text-muted-foreground">Fees {money(s.fees,s.currency)} / Tax {money(s.tax,s.currency)}</p></td><td className="px-3 py-4">{formatDate(s.providerCreatedAt)}{s.settledAt&&<p className="mt-1 text-xs text-muted-foreground">Settled {formatDate(s.settledAt)}</p>}</td><td className="px-3 py-4"><Badge status={s.status}/></td><td className="px-3 py-4">{s.paymentCount}</td><td className="px-3 py-4"><Summary bills={s.vendorBills}/></td><td className="max-w-64 px-3 py-4 text-destructive"><span className="line-clamp-3" title={s.lastErrorMessage??undefined}>{s.lastErrorMessage||"-"}</span></td><td className="px-3 py-4 text-right"><Button variant="outline" size="sm" disabled={!retryable.has(s.status)||actionsPending} onClick={()=>{setActionError("");setTarget(s)}} aria-label={`Retry reconciliation for ${s.providerSettlementId}`}><RotateCcw className="h-4 w-4"/>Retry</Button></td></tr>
{open&&<tr id={`bills-${s.id}`} className="bg-muted/40"><td colSpan={10} className="px-8 py-4"><p className="mb-3 font-semibold">Temple vendor bills</p>{s.vendorBills.length?<div className="overflow-x-auto rounded-md border border-border bg-card"><table className="w-full min-w-[720px]"><thead className="border-b bg-muted text-xs uppercase text-muted-foreground"><tr>{["Temple ID","Amount","Zoho bill ID","Status","Error"].map(h=><th className="px-4 py-2" key={h}>{h}</th>)}</tr></thead><tbody className="divide-y divide-border">{s.vendorBills.map(b=><tr key={b.id}><td className="px-4 py-3 font-mono text-xs">{b.templeId}</td><td className="px-4 py-3">{money(b.amount,s.currency)}</td><td className="px-4 py-3">{b.zohoBillId||"-"}</td><td className="px-4 py-3"><Badge status={b.status}/></td><td className="px-4 py-3 text-destructive">{b.errorMessage||"-"}</td></tr>)}</tbody></table></div>:<p className="text-muted-foreground">No vendor bills are mapped to this settlement.</p>}</td></tr>}</Fragment>})}
{!query.isLoading&&!query.error&&query.data?.items.length===0&&<tr><td colSpan={10} className="px-5 py-10 text-center text-muted-foreground">No settlements match the current filters.</td></tr>}</tbody></table>
<div className="flex items-center justify-between border-t border-border px-5 py-4 text-sm"><span className="text-muted-foreground">Page {page} of {query.data?.meta.totalPages||1} / {query.data?.meta.total??0} settlements</span><div className="flex gap-2"><Button variant="outline" size="sm" disabled={page<=1||query.isFetching} onClick={()=>setPage(v=>Math.max(1,v-1))}>Previous</Button><Button variant="outline" size="sm" disabled={page>=(query.data?.meta.totalPages||1)||query.isFetching} onClick={()=>setPage(v=>v+1)}>Next</Button></div></div></CardContent></Card>
<ActionDialog open={recoverOpen} title="Recover a missed settlement" description="Use this only when a Razorpay settlement is missing because its webhook was not delivered. The Ops API fetches it securely; no Razorpay credentials are used in the browser." onClose={()=>{if(!recover.isPending){setRecoverOpen(false);setRecoveryValidation("")}}}><form className="space-y-4 p-5" onSubmit={e=>{e.preventDefault();const id=recoveryId.trim();if(!/^setl_[A-Za-z0-9]+$/.test(id)){setRecoveryValidation("Enter a valid settlement ID such as setl_123.");return}setRecoveryValidation("");setRecoverOpen(false);setConfirmRecovery(true)}}><label className="block text-sm font-medium" htmlFor="recovery-id">Razorpay settlement ID</label><Input id="recovery-id" value={recoveryId} onChange={e=>{setRecoveryId(e.target.value);setRecoveryValidation("")}} placeholder="setl_123" autoComplete="off" aria-invalid={Boolean(recoveryValidation)} aria-describedby={recoveryValidation?"recovery-error":undefined}/>{recoveryValidation&&<p id="recovery-error" role="alert" className="text-sm text-destructive">{recoveryValidation}</p>}<Button type="submit" className="w-full">Continue</Button></form></ActionDialog>
<ActionDialog open={backfillOpen} title="Sync recent settlements" description="Import recent Razorpay settlements and queue reconciliation asynchronously. Results will appear as processing completes." onClose={()=>{if(!backfill.isPending)setBackfillOpen(false)}}><form className="space-y-4 p-5" onSubmit={e=>{e.preventDefault();backfill.mutate(backfillDays)}}><label className="block text-sm font-medium" htmlFor="backfill-days">Settlement period</label><select id="backfill-days" value={backfillDays} onChange={e=>setBackfillDays(Number(e.target.value))} className="h-10 w-full rounded-md border border-border bg-card px-3 text-sm"><option value={3}>Last 3 days</option><option value={7}>Last 7 days</option><option value={14}>Last 14 days</option></select><Button type="submit" className="w-full" disabled={backfill.isPending}>{backfill.isPending?"Queueing...":"Queue settlement sync"}</Button></form></ActionDialog>
<ConfirmDialog open={confirmRecovery} title="Recover this settlement?" description={"The Ops API will import "+recoveryId.trim()+" from Razorpay and queue reconciliation."} confirmLabel="Recover settlement" pending={recover.isPending} onCancel={()=>{if(!recover.isPending)setConfirmRecovery(false)}} onConfirm={()=>recover.mutate(recoveryId.trim())}/>
<ConfirmDialog open={Boolean(target)} title="Retry settlement reconciliation?" description={`This will retry reconciliation for ${target?.providerSettlementId??"this settlement"}.`} confirmLabel="Retry reconciliation" pending={mutation.isPending} onCancel={()=>{if(!mutation.isPending)setTarget(null)}} onConfirm={()=>{if(target)mutation.mutate(target.id)}}/></>
}
