export const BOOKING_SERVICE = Symbol('BOOKING_SERVICE');
export const BOOKING_LIFECYCLE_SERVICE = Symbol('BOOKING_LIFECYCLE_SERVICE');
export const BOOKING_ZOHO_SYNC_SERVICE = Symbol('BOOKING_ZOHO_SYNC_SERVICE');
export const BOOKING_PAYMENT_ACTIVATION_SERVICE = Symbol(
  'BOOKING_PAYMENT_ACTIVATION_SERVICE',
);

export const BOOKING_INVOICE_SERVICE = Symbol('BOOKING_INVOICE_SERVICE');
