// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import 'dotenv/config';
import { defineConfig } from 'prisma/config';
import { getDatabaseUrl } from './src/config/database-url.config';

const isPrismaGenerate = process.argv.some((arg) => arg.includes('generate'));

export default defineConfig({
  schema: 'src/prisma/schema',
  migrations: {
    path: 'src/prisma/migrations',
  },
  datasource: {
    url: getDatabaseUrl(process.env, { allowPlaceholder: isPrismaGenerate }),
  },
});
