export const SUPPORT_SERVICE = Symbol('SUPPORT_SERVICE');
export const SUPPORT_TICKET_REPOSITORY = Symbol('SUPPORT_TICKET_REPOSITORY');

export const SUPPORT_TICKET_CLEANUP_SERVICE = Symbol(
  'SUPPORT_TICKET_CLEANUP_SERVICE',
);
