import { State } from "country-state-city";
import { Camera, Heart, Lock, MapPin } from "lucide-react";

import type { PoojaTranslation } from "@/lib/api/pooja/poojas.api";

export type BookingDbLanguage = PoojaTranslation["language"];

export const DB_LANGUAGE_BY_APP_LANGUAGE: Record<string, BookingDbLanguage> = {
  en: "EN",
  ml: "ML",
  hi: "HI",
  mr: "MR",
  ta: "TA",
};

export type AstrologicalFieldMode = "NAKSHATRA" | "GOTRA" | "BOTH" | "CUSTOM";

export const ASTROLOGICAL_FIELD_MODE_BY_STATE: Record<
  string,
  AstrologicalFieldMode
> = {
  Kerala: "NAKSHATRA",
  "Tamil Nadu": "NAKSHATRA",
  Karnataka: "BOTH",
  "Andhra Pradesh": "BOTH",
  Telangana: "BOTH",
  Maharashtra: "GOTRA",
  Goa: "GOTRA",
  Gujarat: "GOTRA",
  Rajasthan: "GOTRA",
  "Uttar Pradesh": "GOTRA",
  Uttarakhand: "GOTRA",
  "Madhya Pradesh": "GOTRA",
  Chhattisgarh: "GOTRA",
  Bihar: "GOTRA",
  Jharkhand: "GOTRA",
  Haryana: "GOTRA",
  Punjab: "GOTRA",
  "Himachal Pradesh": "GOTRA",
  "West Bengal": "GOTRA",
  Odisha: "GOTRA",
  Assam: "GOTRA",
  Tripura: "GOTRA",
  Sikkim: "CUSTOM",
  "Arunachal Pradesh": "CUSTOM",
  Manipur: "CUSTOM",
  Meghalaya: "CUSTOM",
  Mizoram: "CUSTOM",
  Nagaland: "CUSTOM",
};

export const ASTROLOGICAL_STATES = Object.keys(
  ASTROLOGICAL_FIELD_MODE_BY_STATE,
);

export const KERALA_NAKSHATRAS = [
  "Aswathi (Ashwini)",
  "Bharani",
  "Karthika (Krittika)",
  "Rohini",
  "Makayiram (Mrigashira)",
  "Thiruvathira (Ardra)",
  "Punartham (Punarvasu)",
  "Pooyam (Pushya)",
  "Ayilyam (Ashlesha)",
  "Makham (Magha)",
  "Pooram (Purva Phalguni)",
  "Uthram (Uttara Phalguni)",
  "Atham (Hasta)",
  "Chithira (Chitra)",
  "Chothi (Swati)",
  "Vishakham (Vishakha)",
  "Anizham (Anuradha)",
  "Thrikketta (Jyeshtha)",
  "Moolam (Mula)",
  "Pooradam (Purva Ashadha)",
  "Uthradam (Uttara Ashadha)",
  "Thiruvonam (Shravana)",
  "Avittam (Dhanishtha)",
  "Chathayam (Shatabhisha)",
  "Pooruruttathi (Purva Bhadrapada)",
  "Uthrattathi (Uttara Bhadrapada)",
  "Revathi (Revati)",
];

export const TAMIL_NADU_NAKSHATRAS = [
  "Aswini (Ashwini)",
  "Bharani",
  "Karthigai (Krittika)",
  "Rohini",
  "Mirugasirisham (Mrigashira)",
  "Thiruvathirai (Ardra)",
  "Punarpoosam (Punarvasu)",
  "Poosam (Pushya)",
  "Ayilyam (Ashlesha)",
  "Magam (Magha)",
  "Pooram (Purva Phalguni)",
  "Uthiram (Uttara Phalguni)",
  "Hastham (Hasta)",
  "Chithirai (Chitra)",
  "Swathi (Swati)",
  "Visakam (Vishakha)",
  "Anusham (Anuradha)",
  "Kettai (Jyeshtha)",
  "Moolam (Mula)",
  "Pooradam (Purva Ashadha)",
  "Uthiradam (Uttara Ashadha)",
  "Thiruvonam (Shravana)",
  "Avittam (Dhanishtha)",
  "Sadayam (Shatabhisha)",
  "Poorattathi (Purva Bhadrapada)",
  "Uthirattathi (Uttara Bhadrapada)",
  "Revathi (Revati)",
];

export const GOTRAS = [
  "Agastya",
  "Ahabhunasa",
  "Alambani",
  "Angirasa",
  "Atri",
  "Atreya",
  "Aupamanyava",
  "Babhravya",
  "Bharadwaj / Bharadvaja",
  "Bhargava",
  "Bhrigu",
  "Bhaskara",
  "Chandilya / Shandilya",
  "Chikitasa",
  "Chyavana",
  "Dalabhya",
  "Darbhas",
  "Dhananjaya",
  "Dhanvantari",
  "Galvasaya",
  "Garg / Garga",
  "Gautam / Gautama",
  "Harita / Haritasa",
  "Jamadagni",
  "Jatukarna",
  "Kalabodhana",
  "Kanva",
  "Kapi",
  "Kapila",
  "Kapinjala",
  "Kashyap / Kashyapa",
  "Katyayana",
  "Kaundinya / Koundinya",
  "Kaushika / Kaushik / Koushik",
  "Kaustubha",
  "Kavist",
  "Krishnatreya",
  "Kusha",
  "Kutsa",
  "Kutsasa",
  "Lomasha",
  "Mandavya",
  "Marichi",
  "Markandeya",
  "Matanga",
  "Maudgalya / Mudgalya",
  "Mudgal / Mudgala",
  "Naidhruva",
  "Naidhruva Kashyapa",
  "Nithunthana / Naithunthasa",
  "Parashara",
  "Pulaha",
  "Pulastya",
  "Rathitara",
  "Salankayana",
  "Sanaka",
  "Sanatana",
  "Sanjaya",
  "Sankhyayana",
  "Sankriti / Sankrityayan",
  "Savarna",
  "Shaunaka",
  "Shatamarshana",
  "Srivatsa",
  "Suryadhwaja",
  "Upamanyu",
  "Vadula / Vatula",
  "Valmiki",
  "Vardhulasa",
  "Vartantu",
  "Vashishtha / Vasistha",
  "Vatsa",
  "Vatsyayan",
  "Veetahavya",
  "Vishnu",
  "Vishnuvardhana",
  "Vishwagni",
  "Vishvamitra / Vishwamitra",
  "Yaska",
  "Other - Enter manually",
  "Don't know Gotra",
];

export const INDIAN_STATES = State.getStatesOfCountry("IN");

export const SESSION_EXPIRED_ERROR = "Session Expired";

export const BOOKING_TRUST_ITEM_ICONS = [Lock, MapPin, Camera, Heart];

export const DEFAULT_BOOKING_FORM = {
  name: "",
  whatsappNumber: "",
  state: "",
  naal: "",
  sankalpa: "",
  wantsPrasad: false,
  houseNo: "",
  streetName: "",
  pincode: "",
  district: "",
  deliveryState: "",
  phoneNumber: "",
};
